-- DDL generated by Postico 1.5.21
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE feeds (
    title text,
    description text,
    link text,
    id text,
    author text,
    published text,
    updated text,
    category text,
    content_type text,
    content_value text,
    comments text,
    source text,
    contributors text,
    rights text,
    attachments text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX idx_feeds_id ON feeds(id text_ops);
CREATE INDEX feeds_title_index ON feeds USING GIN ((to_tsvector('english'::regconfig, title)) tsvector_ops);
CREATE INDEX feeds_description_index ON feeds USING GIN ((to_tsvector('english'::regconfig, description)) tsvector_ops);
CREATE INDEX feeds_content_value_index ON feeds USING GIN ((to_tsvector('english'::regconfig, content_value)) tsvector_ops);
CREATE INDEX feeds_author_index ON feeds USING GIN ((to_tsvector('english'::regconfig, author)) tsvector_ops);
